
<div align="center">
  <img src="https://github.com/hitsz-ids/synthetic-data-generator/blob/main/assets/sdg_logo.png?raw=true" width="400" >
</div>
<div align="center">





# 🚀 Synthetic data generation without Raw Data using LLM




The Synthetic Data Generator (SDG) is a specialized framework designed to generate high-quality structured tabular data. It incorporates a wide range of single-table, multi-table data synthesis algorithms and LLM-based synthetic data generation models.

Synthetic data, generated by machines using real data, metadata, and algorithms, does not contain any sensitive information, yet it retains the essential characteristics of the original data. There is no direct correlation between synthetic data and real data, making it exempt from privacy regulations such as GDPR and ADPPA. This eliminates the risk of privacy breaches in practical applications.

In [ ]:
# install dependencies
# !pip install sdgx
# OR
!pip install git+https://github.com/hitsz-ids/synthetic-data-generator.git

Collecting git+https://github.com/hitsz-ids/synthetic-data-generator.git
  Cloning https://github.com/hitsz-ids/synthetic-data-generator.git to /tmp/pip-req-build-mn8ro352
  Running command git clone --filter=blob:none --quiet https://github.com/hitsz-ids/synthetic-data-generator.git /tmp/pip-req-build-mn8ro352
  Resolved https://github.com/hitsz-ids/synthetic-data-generator.git to commit 54ee09b185ee33d5d7027f456c1bd263c8e571d8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (8.1.7)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (2.2.1)
Collecting faker>=10 (from sdgx==0.1.6.dev0)
  Downloading Faker-23.2.1-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 23.7 MB/s eta 0:00:00
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (7.0.1)
Collecting loguru (from sdgx==0.1.6.dev0)
  Downloading loguru-0.7.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 5.7 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (3.7.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (1.25.2)
Collecting openai>=1.10.0 (from sdgx==0.1.6.dev0)
  Downloading openai-1.12.0-py3-none-any.whl (226 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.7/226.7 kB 19.4 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (1.5.3)
Requirement already satisfied: pluggy in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (1.4.0)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (14.0.2)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (2.6.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (6.0.1)
Requirement already satisfied: scikit-learn<2,>=0.24 in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (1.11.4)
Collecting table-evaluator (from sdgx==0.1.6.dev0)
  Downloading table_evaluator-1.6.1-py3-none-any.whl (22 kB)
Requirement already satisfied: torch>=2 in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (2.1.0+cu121)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sdgx==0.1.6.dev0) (0.16.0+cu121)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker>=10->sdgx==0.1.6.dev0) (2.8.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai>=1.10.0->sdgx==0.1.6.dev0) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai>=1.10.0->sdgx==0.1.6.dev0) (1.7.0)
Collecting httpx<1,>=0.23.0 (from openai>=1.10.0->sdgx==0.1.6.dev0)
  Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 8.6 MB/s eta 0:00:00
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai>=1.10.0->sdgx==0.1.6.dev0) (1.3.0)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai>=1.10.0->sdgx==0.1.6.dev0) (4.66.2)
Requirement already satisfied: typing-extensions<5,>=4.7 in /usr/local/lib/python3.10/dist-packages (from openai>=1.10.0->sdgx==0.1.6.dev0) (4.9.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2->sdgx==0.1.6.dev0) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.2 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2->sdgx==0.1.6.dev0) (2.16.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=0.24->sdgx==0.1.6.dev0) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=0.24->sdgx==0.1.6.dev0) (3.3.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=2->sdgx==0.1.6.dev0) (3.13.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2->sdgx==0.1.6.dev0) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2->sdgx==0.1.6.dev0) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2->sdgx==0.1.6.dev0) (3.1.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=2->sdgx==0.1.6.dev0) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2->sdgx==0.1.6.dev0) (2.1.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata->sdgx==0.1.6.dev0) (3.17.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sdgx==0.1.6.dev0) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sdgx==0.1.6.dev0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sdgx==0.1.6.dev0) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sdgx==0.1.6.dev0) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sdgx==0.1.6.dev0) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sdgx==0.1.6.dev0) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->sdgx==0.1.6.dev0) (3.1.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->sdgx==0.1.6.dev0) (2023.4)
Collecting pandas (from sdgx==0.1.6.dev0)
  Downloading pandas-2.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 53.7 MB/s eta 0:00:00
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from table-evaluator->sdgx==0.1.6.dev0) (5.9.5)
Collecting dython==0.7.3 (from table-evaluator->sdgx==0.1.6.dev0)
  Downloading dython-0.7.3-py3-none-any.whl (23 kB)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from table-evaluator->sdgx==0.1.6.dev0) (0.13.1)
Collecting tzdata>=2022.1 (from pandas->sdgx==0.1.6.dev0)
  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 21.0 MB/s eta 0:00:00
Collecting scikit-plot>=0.3.7 (from dython==0.7.3->table-evaluator->sdgx==0.1.6.dev0)
  Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torchvision->sdgx==0.1.6.dev0) (2.31.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai>=1.10.0->sdgx==0.1.6.dev0) (3.6)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai>=1.10.0->sdgx==0.1.6.dev0) (1.2.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai>=1.10.0->sdgx==0.1.6.dev0) (2024.2.2)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai>=1.10.0->sdgx==0.1.6.dev0)
  Downloading httpcore-1.0.4-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 9.6 MB/s eta 0:00:00
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.10.0->sdgx==0.1.6.dev0)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 7.7 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker>=10->sdgx==0.1.6.dev0) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2->sdgx==0.1.6.dev0) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision->sdgx==0.1.6.dev0) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision->sdgx==0.1.6.dev0) (2.0.7)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2->sdgx==0.1.6.dev0) (1.3.0)
Building wheels for collected packages: sdgx
  Building wheel for sdgx (pyproject.toml) ... done
  Created wheel for sdgx: filename=sdgx-0.1.6.dev0-py3-none-any.whl size=216340 sha256=c75711a6da80c72d5cfcdf3569ad74071e0f2d3af2fa397dfba4ee86b261a5cc
  Stored in directory: /tmp/pip-ephem-wheel-cache-zn399xje/wheels/a3/7c/29/b6529b1098dfaed856ca7c2c6dfd0113422a7a8f29d63c6a5c
Successfully built sdgx
Installing collected packages: tzdata, loguru, h11, pandas, httpcore, faker, scikit-plot, httpx, openai, dython, table-evaluator, sdgx
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible.
Successfully installed dython-0.7.3 faker-23.2.1 h11-0.14.0 httpcore-1.0.4 httpx-0.27.0 loguru-0.7.2 openai-1.12.0 pandas-2.0.3 scikit-plot-0.3.7 sdgx-0.1.6.dev0 table-evaluator-1.6.1 tzdata-2024.1

We demonstrate with a single table synthetic example.

# LLM-integrated synthetic data generation

For a long time, LLM has been used to understand and generate various types of data.

In fact, LLM also has certain capabilities in tabular data generation. LLM has some abilities that cannot be achieved by traditional (GAN-based models or statistical models) .

In [ ]:
# please set your openAI key here:

OPEN_AI_KEY = ""
OPEN_AI_BASE = "https://api.openai.com/v1/"

In [ ]:
# import packages

import pandas as pd
from sdgx.utils import download_demo_data
from sdgx.data_models.metadata import Metadata
from sdgx.models.LLM.single_table.gpt import SingleTableGPTModel

# read the demo data
# currently we use the well-known adult dataset as a example
data_path = download_demo_data()
df = pd.read_csv(data_path)
metadata = Metadata.from_dataframe(df)

2024-02-27 08:04:47.112 | INFO     | sdgx.utils:download_demo_data:68 - Downloading demo data from github data source to /content/dataset/adult.csv


# Synthetic data generation without Data


Our `sdgx.models.LLM.single_table.gpt.SingleTableGPTModel` implements “Synthetic data generation without Raw Data”.

No training data is required, synthetic data can be generated based on metadata data.

![LLM_Case_1](https://github.com/hitsz-ids/synthetic-data-generator/blob/main/assets/LLM_Case_1.gif?raw=true)

In [ ]:
model = SingleTableGPTModel()
model.set_openAI_settings(OPEN_AI_BASE, OPEN_AI_KEY)
model.gpt_model = "gpt-3.5-turbo"

In [ ]:
model.fit(metadata)
# this may take a while
sampled_data = model.sample(30)

2024-02-27 08:05:01.632 | INFO     | sdgx.models.LLM.single_table.gpt:_fit_with_metadata:228 - Fitting model with metadata...
2024-02-27 08:05:01.640 | INFO     | sdgx.models.LLM.single_table.gpt:_fit_with_metadata:232 - Fitting model with metadata... Finished.
2024-02-27 08:05:01.643 | INFO     | sdgx.models.LLM.single_table.gpt:sample:385 - Sampling use GPT model ...
2024-02-27 08:05:01.647 | INFO     | sdgx.models.LLM.single_table.gpt:_sample_with_metadata:446 - Sampling with metadata.
2024-02-27 08:05:01.652 | INFO     | sdgx.models.LLM.base:_form_dataset_description:122 - No dataset_description given in current model.
2024-02-27 08:05:01.656 | INFO     | sdgx.models.LLM.base:_form_message_with_offtable_features:108 - No off_table_feature needed in current model.
2024-02-27 08:05:01.724 | INFO     | sdgx.models.LLM.single_table.gpt:ask_gpt:163 - Ask GPT with temperature = 0.1.
2024-02-27 08:05:48.080 | INFO     | sdgx.models.LLM.single_table.gpt:ask_gpt:176 - Ask GPT Finished.
2024-02-27 08:05:48.082 | INFO     | sdgx.models.LLM.single_table.gpt:extract_samples_from_response:357 - Extracting samples from response ...
2024-02-27 08:05:48.094 | INFO     | sdgx.models.LLM.single_table.gpt:extract_samples_from_response:369 - Extracting samples from response ... Finished, 29 extracted.
2024-02-27 08:05:48.099 | INFO     | sdgx.models.LLM.single_table.gpt:sample:395 - Sampling use GPT model ... Finished.

In [ ]:
sampled_data

,educational-num,income,occupation,relationship,workclass,fnlwgt,gender,hours-per-week,capital-loss,marital-status,capital-gain,education,age,native-country,race
0,12,<=50K,Sales,Not-in-family,Private,234721,Female,40,0,Never-married,2174,HS-grad,25,United-States,White
1,10,<=50K,Craft-repair,Husband,Self-emp-not-inc,338409,Male,13,0,Married-civ-spouse,0,Some-college,38,United-States,White
2,13,>50K,Exec-managerial,Wife,Private,284582,Female,40,0,Married-civ-spouse,0,Bachelors,28,Cuba,Black
3,10,<=50K,Other-service,Not-in-family,Private,160187,Female,40,0,Never-married,0,10th,32,United-States,Black
4,12,<=50K,Adm-clerical,Own-child,Private,209642,Male,40,0,Never-married,0,HS-grad,18,United-States,White
5,6,<=50K,Handlers-cleaners,Unmarried,Private,45781,Female,30,0,Never-married,0,11th,29,United-States,Black
6,9,<=50K,Sales,Other-relative,Self-emp-not-inc,159449,Male,40,0,Not-in-family,0,HS-grad,34,United-States,White
7,10,<=50K,Craft-repair,Unmarried,Private,280464,Male,45,0,Never-married,0,Some-college,63,United-States,White
8,4,<=50K,Other-service,Own-child,Local-gov,141297,Female,35,0,Never-married,0,7th-8th,24,United-States,White
9,13,>50K,Prof-specialty,Husband,Private,122272,Male,60,0,Married-civ-spouse,7688,Bachelors,59,United-States,White
10,9,<=50K,Craft-repair,Not-in-family,Private,205019,Male,20,0,Never-married,0,HS-grad,20,United-States,White
11,14,>50K,Exec-managerial,Wife,Private,245487,Female,55,0,Married-civ-spouse,3103,Masters,52,United-States,White
12,13,>50K,Prof-specialty,Husband,Private,176756,Male,45,0,Married-civ-spouse,0,Doctorate,31,United-States,White
13,9,<=50K,Other-service,Not-in-family,Private,186824,Female,40,0,Never-married,0,HS-grad,46,United-States,White
14,10,<=50K,Adm-clerical,Unmarried,Private,28887,Female,50,0,Never-married,0,Some-college,29,United-States,White
15,13,>50K,Exec-managerial,Husband,Private,292175,Male,60,0,Married-civ-spouse,7688,Bachelors,36,United-States,White
16,14,>50K,Prof-specialty,Wife,Private,189346,Female,55,0,Married-civ-spouse,3103,Masters,42,United-States,White
17,9,<=50K,Other-service,Not-in-family,Private,29054,Female,40,0,Never-married,0,HS-grad,40,United-States,White
18,10,<=50K,Adm-clerical,Unmarried,Private,56352,Female,50,0,Never-married,0,Some-college,45,United-States,White
19,13,>50K,Exec-managerial,Husband,Private,122272,Male,60,0,Married-civ-spouse,7688,Bachelors,55,United-States,White
20,14,>50K,Prof-specialty,Wife,Private,245487,Female,55,0,Married-civ-spouse,3103,Masters,50,United-States,White
21,9,<=50K,Other-service,Not-in-family,Private,176756,Female,40,0,Never-married,0,HS-grad,60,United-States,White
22,10,<=50K,Adm-clerical,Unmarried,Private,186824,Female,50,0,Never-married,0,Some-college,35,United-States,White
23,13,>50K,Exec-managerial,Husband,Private,28887,Male,60,0,Married-civ-spouse,7688,Bachelors,41,United-States,White
24,14,>50K,Prof-specialty,Wife,Private,29054,Female,55,0,Married-civ-spouse,3103,Masters,30,United-States,White
25,9,<=50K,Other-service,Not-in-family,Private,56352,Female,40,0,Never-married,0,HS-grad,27,United-States,White
26,10,<=50K,Adm-clerical,Unmarried,Private,122272,Female,50,0,Never-married,0,Some-college,39,United-States,White
27,13,>50K,Exec-managerial,Husband,Private,245487,Male,60,0,Married-civ-spouse,7688,Bachelors,48,United-States,White
28,14,>50K,Prof-specialty,Wife,Private,186824,Female,55,0,Married-civ-spouse,3103,Masters,37,United-States,White

View the original information returned by gpt through the `_responses` attribute.

In [ ]:
model._responses

[ChatCompletion(id='chatcmpl-8wmkQ05gBA2dYa6BPAjzaKQrlgCop', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='educational-num is 12, income is <=50K, occupation is Sales, relationship is Not-in-family, workclass is Private, fnlwgt is 234721, gender is Female, hours-per-week is 40, capital-loss is 0, marital-status is Never-married, capital-gain is 2174, education is HS-grad, age is 25, native-country is United-States, race is White\neducational-num is 10, income is <=50K, occupation is Craft-repair, relationship is Husband, workclass is Self-emp-not-inc, fnlwgt is 338409, gender is Male, hours-per-week is 13, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 0, education is Some-college, age is 38, native-country is United-States, race is White\neducational-num is 13, income is >50K, occupation is Exec-managerial, relationship is Wife, workclass is Private, fnlwgt is 284582, gender is Female, hours-per-week is 40, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 0, education is Bachelors, age is 28, native-country is Cuba, race is Black\neducational-num is 10, income is <=50K, occupation is Other-service, relationship is Not-in-family, workclass is Private, fnlwgt is 160187, gender is Female, hours-per-week is 40, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is 10th, age is 32, native-country is United-States, race is Black\neducational-num is 12, income is <=50K, occupation is Adm-clerical, relationship is Own-child, workclass is Private, fnlwgt is 209642, gender is Male, hours-per-week is 40, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is HS-grad, age is 18, native-country is United-States, race is White\neducational-num is 6, income is <=50K, occupation is Handlers-cleaners, relationship is Unmarried, workclass is Private, fnlwgt is 45781, gender is Female, hours-per-week is 30, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is 11th, age is 29, native-country is United-States, race is Black\neducational-num is 9, income is <=50K, occupation is Sales, relationship is Other-relative, workclass is Self-emp-not-inc, fnlwgt is 159449, gender is Male, hours-per-week is 40, capital-loss is 0, marital-status is Not-in-family, capital-gain is 0, education is HS-grad, age is 34, native-country is United-States, race is White\neducational-num is 10, income is <=50K, occupation is Craft-repair, relationship is Unmarried, workclass is Private, fnlwgt is 280464, gender is Male, hours-per-week is 45, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is Some-college, age is 63, native-country is United-States, race is White\neducational-num is 4, income is <=50K, occupation is Other-service, relationship is Own-child, workclass is Local-gov, fnlwgt is 141297, gender is Female, hours-per-week is 35, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is 7th-8th, age is 24, native-country is United-States, race is White\neducational-num is 13, income is >50K, occupation is Prof-specialty, relationship is Husband, workclass is Private, fnlwgt is 122272, gender is Male, hours-per-week is 60, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 7688, education is Bachelors, age is 59, native-country is United-States, race is White\neducational-num is 9, income is <=50K, occupation is Craft-repair, relationship is Not-in-family, workclass is Private, fnlwgt is 205019, gender is Male, hours-per-week is 20, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is HS-grad, age is 20, native-country is United-States, race is White\neducational-num is 14, income is >50K, occupation is Exec-managerial, relationship is Wife, workclass is Private, fnlwgt is 245487, gender is Female, hours-per-week is 55, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 3103, education is Masters, age is 52, native-country is United-States, race is White\neducational-num is 13, income is >50K, occupation is Prof-specialty, relationship is Husband, workclass is Private, fnlwgt is 176756, gender is Male, hours-per-week is 45, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 0, education is Doctorate, age is 31, native-country is United-States, race is White\neducational-num is 9, income is <=50K, occupation is Other-service, relationship is Not-in-family, workclass is Private, fnlwgt is 186824, gender is Female, hours-per-week is 40, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is HS-grad, age is 46, native-country is United-States, race is White\neducational-num is 10, income is <=50K, occupation is Adm-clerical, relationship is Unmarried, workclass is Private, fnlwgt is 28887, gender is Female, hours-per-week is 50, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is Some-college, age is 29, native-country is United-States, race is White\neducational-num is 13, income is >50K, occupation is Exec-managerial, relationship is Husband, workclass is Private, fnlwgt is 292175, gender is Male, hours-per-week is 60, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 7688, education is Bachelors, age is 36, native-country is United-States, race is White\neducational-num is 14, income is >50K, occupation is Prof-specialty, relationship is Wife, workclass is Private, fnlwgt is 189346, gender is Female, hours-per-week is 55, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 3103, education is Masters, age is 42, native-country is United-States, race is White\neducational-num is 9, income is <=50K, occupation is Other-service, relationship is Not-in-family, workclass is Private, fnlwgt is 29054, gender is Female, hours-per-week is 40, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is HS-grad, age is 40, native-country is United-States, race is White\neducational-num is 10, income is <=50K, occupation is Adm-clerical, relationship is Unmarried, workclass is Private, fnlwgt is 56352, gender is Female, hours-per-week is 50, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is Some-college, age is 45, native-country is United-States, race is White\neducational-num is 13, income is >50K, occupation is Exec-managerial, relationship is Husband, workclass is Private, fnlwgt is 122272, gender is Male, hours-per-week is 60, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 7688, education is Bachelors, age is 55, native-country is United-States, race is White\neducational-num is 14, income is >50K, occupation is Prof-specialty, relationship is Wife, workclass is Private, fnlwgt is 245487, gender is Female, hours-per-week is 55, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 3103, education is Masters, age is 50, native-country is United-States, race is White\neducational-num is 9, income is <=50K, occupation is Other-service, relationship is Not-in-family, workclass is Private, fnlwgt is 176756, gender is Female, hours-per-week is 40, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is HS-grad, age is 60, native-country is United-States, race is White\neducational-num is 10, income is <=50K, occupation is Adm-clerical, relationship is Unmarried, workclass is Private, fnlwgt is 186824, gender is Female, hours-per-week is 50, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is Some-college, age is 35, native-country is United-States, race is White\neducational-num is 13, income is >50K, occupation is Exec-managerial, relationship is Husband, workclass is Private, fnlwgt is 28887, gender is Male, hours-per-week is 60, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 7688, education is Bachelors, age is 41, native-country is United-States, race is White\neducational-num is 14, income is >50K, occupation is Prof-specialty, relationship is Wife, workclass is Private, fnlwgt is 29054, gender is Female, hours-per-week is 55, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 3103, education is Masters, age is 30, native-country is United-States, race is White\neducational-num is 9, income is <=50K, occupation is Other-service, relationship is Not-in-family, workclass is Private, fnlwgt is 56352, gender is Female, hours-per-week is 40, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is HS-grad, age is 27, native-country is United-States, race is White\neducational-num is 10, income is <=50K, occupation is Adm-clerical, relationship is Unmarried, workclass is Private, fnlwgt is 122272, gender is Female, hours-per-week is 50, capital-loss is 0, marital-status is Never-married, capital-gain is 0, education is Some-college, age is 39, native-country is United-States, race is White\neducational-num is 13, income is >50K, occupation is Exec-managerial, relationship is Husband, workclass is Private, fnlwgt is 245487, gender is Male, hours-per-week is 60, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 7688, education is Bachelors, age is 48, native-country is United-States, race is White\neducational-num is 14, income is >50K, occupation is Prof-specialty, relationship is Wife, workclass is Private, fnlwgt is 186824, gender is Female, hours-per-week is 55, capital-loss is 0, marital-status is Married-civ-spouse, capital-gain is 3103, education is Masters, age is 37, native-country is United-States, race is White', role='assistant', function_call=None, tool_calls=None))], created=1709021102, model='gpt-3.5-turbo-0125', object='chat.completion', system_fingerprint='fp_86156a94a0', usage=CompletionUsage(completion_tokens=2640, prompt_tokens=269, total_tokens=2909))]